# Generated by Django 3.2.4 on 2021-06-10 16:01

import conf.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='imagen',
            field=models.ImageField(null=True, upload_to=conf.utils.drive_upload_image),
        ),
    ]
