# Generated by Django 3.2.4 on 2021-06-11 00:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_negocio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0, 'min value violated')]),
        ),
    ]
