# Generated by Django 3.2.4 on 2021-06-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
