# Generated by Django 3.2.4 on 2021-06-13 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210612_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mont_exist',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='method_cont',
            field=models.CharField(default='und', max_length=50, verbose_name='Unidad'),
        ),
    ]
