# Generated by Django 3.2.4 on 2021-06-16 20:46
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0009_alter_detalleventa_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
