# Generated by Django 3.2.4 on 2021-06-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210616_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='negocio',
            old_name='decripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='negocio',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='imagen',
        ),
        migrations.AddField(
            model_name='negocio',
            name='image',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='negocio',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='negocio',
            name='social_reason',
            field=models.CharField(default='something', max_length=350),
            preserve_default=False,
        ),
    ]
