# Generated by Django 3.2.4 on 2021-06-20 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20210620_0128'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'category'), ('name',)},
        ),
    ]
