# Generated by Django 3.2.4 on 2021-06-22 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_product_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='business',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='dashboard.negocio'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('type_document', models.CharField(blank=True, max_length=150, null=True)),
                ('num_document', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('direction', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('type_contact', models.CharField(blank=True, choices=[('DNI', 'DNI'), ('RUC', 'El RUC')], default='DNI', max_length=150, null=True)),
                ('notes', models.TextField(blank=True, max_length=400, null=True)),
            ],
            options={
                'unique_together': {('name', 'num_document')},
            },
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='dashboard.contact'),
        ),
    ]
