# Generated by Django 3.2.4 on 2021-06-22 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20210622_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='tipo_documento',
        ),
        migrations.AlterField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.contact'),
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='TipoDocumento',
        ),
    ]
