# Generated by Django 3.2.4 on 2021-06-22 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20210622_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='business',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='dashboard.negocio'),
            preserve_default=False,
        ),
    ]
