# Generated by Django 3.2.4 on 2021-06-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_contact_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type_contact',
            field=models.CharField(blank=True, choices=[('Proveedor', 'PROVEEDOR'), ('Cliente', 'CLIENTE')], default='Cliente', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type_document',
            field=models.CharField(blank=True, choices=[('DNI', 'DNI'), ('RUC', 'RUC')], default='DNI', max_length=150, null=True),
        ),
    ]
