# Generated by Django 3.2.4 on 2021-06-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20210623_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type_contact',
            field=models.CharField(blank=True, choices=[('Proveedor', 'PROVIDER'), ('Cliente', 'CLIENTE')], default='Cliente', max_length=150, null=True),
        ),
    ]
