# Generated by Django 3.2.4 on 2021-06-24 05:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_contact_type_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='type_contact',
            field=models.CharField(blank=True, choices=[('PROVIDER', 'PROVIDER'), ('CLIENT', 'CLIENTE')], default='CLIENT', max_length=150, null=True),
        ),
    ]
