# Generated by Django 3.2.4 on 2021-06-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='num_document',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set(),
        ),
    ]
