# Generated by Django 3.2.4 on 2021-06-28 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20210625_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_bussiness',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_staff',
        ),
    ]
