# Generated by Django 3.2.4 on 2021-06-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20210628_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='validated',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
