# Generated by Django 3.2.4 on 2021-07-02 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_usuario_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='business',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='dashboard.negocio'),
            preserve_default=False,
        ),
    ]
