# Generated by Django 3.2.4 on 2021-07-02 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_brand_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='business',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='dashboard.negocio'),
            preserve_default=False,
        ),
    ]
