# Generated by Django 3.2.5 on 2021-07-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_alter_venta_fecha_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField(null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('client_name', models.CharField(max_length=250)),
                ('count', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
    ]
