# Generated by Django 3.2.5 on 2021-07-03 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_saleview'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='user',
            field=models.ForeignKey(default=61, on_delete=django.db.models.deletion.CASCADE, to='dashboard.usuario'),
            preserve_default=False,
        ),
    ]
