# Generated by Django 3.2.5 on 2021-07-03 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20210703_0303'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set(),
        ),
    ]
