# Generated by Django 3.2.5 on 2021-07-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auto_20210706_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='state_payment',
        ),
        migrations.AddField(
            model_name='venta',
            name='state_payment',
            field=models.BooleanField(default=False),
        ),
    ]
