# Generated by Django 3.2.5 on 2021-07-06 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_auto_20210706_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='type_payment',
            name='business',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='dashboard.negocio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='type_payment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
